project_type: ruby
test:
  bundle-audit:
    command: bundle-audit check --update | tee .framgia-ci-reports/bundle-audit.txt
  rspec:
    command: bundle exec rspec --format html --out .framgia-ci-reports/rspec.html spec/
  brakeman:
    command: bundle exec brakeman -o .framgia-ci-reports/brakeman.html -o .framgia-ci-reports/brakeman.json
  reek:
    command: bundle exec reek -c config.reek --format html > .framgia-ci-reports/reek.html app/
  rubocop:
    command: bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color --rails --out .framgia-ci-reports/rubocop.xml app/ lib/
  scss-lint:
    command: bundle exec scss-lint --require=scss_lint_reporter_checkstyle --format=Checkstyle --out=.framgia-ci-reports/scss-lint.xml app/assets/stylesheets/
  eslint:
    command: eslint --format=checkstyle --output-file=.framgia-ci-reports/eslint.xml app/
  rails_best_practices:
    command: bundle exec rails_best_practices --format html -e "app/models/application_record.rb,app/models/group_user.rb,app/controllers/pages_controller.rb,app/controllers/groups_controller.rb,app/controllers/users_controller.rb,app/controllers/sessions_controller.rb,app/controllers/static_pages_controller.rb,app/helpers/sessions_helper.rb,app/models/user.rb" --output-file .framgia-ci-reports/rails_best_practices.html app/
